version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb
    networks:
      - backend

  nestjs-app:
    build: ./msa
    container_name: msa
    ports:
      - "3000:3000"
    volumes:
      - ./msa:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend: